import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { createClient } from '@supabase/supabase-js';
import JsBarcode from 'jsbarcode';
import { Html5Qrcode, Html5QrcodeSupportedFormats } from 'html5-qrcode';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { supabase } from './supabaseClient';

// --- GLOBAL UTILS ---
const safeJSONParse = (key, fallback) => {
  try {
    const item = localStorage.getItem(key);
    if (!item || item === 'undefined' || item === 'null') return fallback;
    return JSON.parse(item);
  } catch (e) {
    localStorage.removeItem(key); 
    return fallback;
  }
};

// --- CONSTANTS ---
const QUALITIES = ['Virgin', 'Fresh', 'Semi Fresh', 'Semi 2', 'Semi Star', 'UV Fabric'];
const COLORS = [
  'White', 'Ivory', 'Red', 'Maroon', 'Orange', 'Lemon Yellow', 'Golden Yellow', 
  'Bottle Green', 'Sea Green', 'Medical Blue', 'Royal Blue', 'Peacock Blue', 
  'Navy Blue', 'Beige', 'Coffee Brown', 'Gray', 'Black', 'Colour Change'
];

// --- DATA SERVICE ---
const DataService = {
  async getStock() {
    const { data, error } = await supabase.from('rolls').select('*').order('updated_at', { ascending: false });
    return error ? [] : data;
  },
  async addRoll(roll, deviceName) {
    const rollWithDevice = { ...roll, device_name: deviceName, updated_at: new Date() };
    const { data, error } = await supabase.from('rolls').insert([rollWithDevice]).select();
    if (error) throw error;
    return data[0];
  },
  async updateRoll(id, updates, deviceName) {
    const updatesWithDevice = { ...updates, device_name: deviceName, updated_at: new Date() };
    const { error } = await supabase.from('rolls').update(updatesWithDevice).eq('id', id);
    if (error) throw error;
  },
  async deleteRoll(id) {
    await supabase.from('rolls').delete().eq('id', id);
  },
  async getRawMaterials() {
    const { data, error } = await supabase.from('raw_materials').select('*').order('name');
    return error ? [] : data;
  },
  async addRawMaterial(name) {
      const newMat = { name, stock_quantity: 0, unit: 'kg' };
      await supabase.from('raw_materials').insert([newMat]);
  },
  async updateRawMaterial(id, qty, isAddition, deviceName) {
    const { data } = await supabase.from('raw_materials').select('stock_quantity').eq('id', id).single();
    const currentQty = data ? parseFloat(data.stock_quantity) : 0;
    const newQty = currentQty + (isAddition ? parseFloat(qty) : -parseFloat(qty));
    await supabase.from('raw_materials').update({ stock_quantity: newQty, last_updated_by: deviceName }).eq('id', id);
  }
};

// --- HELPER: GENERATE PDF CHALLAN ---
const generateChallan = (rolls, details) => {
    try {
        const doc = new jsPDF();
        doc.setFontSize(22);
        doc.text("KSF NON WOVEN", 105, 20, null, null, "center");
        doc.setFontSize(12);
        doc.text("Shahjahanpur, Uttar Pradesh", 105, 28, null, null, "center");
        doc.text("DISPATCH CHALLAN / GATE PASS", 105, 36, null, null, "center");
        doc.setFontSize(10);
        doc.text(`Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, 50);
        doc.text(`Buyer: ${details.buyer}`, 14, 56);
        doc.text(`Vehicle No: ${details.vehicle}`, 14, 62);
        doc.text(`Generated By: ${details.device}`, 14, 68);
        const tableData = rolls.map((r, i) => [i + 1, r.product_id || '-', r.quality || '-', r.color || '-', `${r.width_inches || 0}"`, `${r.gsm || 0}`, `${r.net_weight || 0} kg`]);
        doc.autoTable({ startY: 75, head: [['#', 'Roll ID', 'Quality', 'Color', 'Size', 'GSM', 'Weight']], body: tableData, theme: 'grid', headStyles: { fillColor: [41, 128, 185] } });
        const finalY = (doc.lastAutoTable && doc.lastAutoTable.finalY) ? doc.lastAutoTable.finalY : 150;
        const totalWt = rolls.reduce((sum, r) => sum + Number(r.net_weight || 0), 0);
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.text(`Total Rolls: ${rolls.length}`, 14, finalY + 10);
        doc.text(`Total Weight: ${totalWt.toLocaleString()} kg`, 150, finalY + 10);
        doc.setFont(undefined, 'normal');
        doc.text("Authorized Signatory", 14, finalY + 30);
        doc.text("Receiver's Signature", 150, finalY + 30);
        const cleanName = (details.buyer || 'Unknown').replace(/[^a-z0-9]/gi, '_');
        doc.save(`KSF_GatePass_${cleanName}_${Date.now()}.pdf`);
        return true;
    } catch (err) {
        alert("PDF Error: " + err.message);
        return false;
    }
};

// --- COMPONENTS ---
const Header = React.memo(({ user, isGuest, deviceName, onLogout, setTab, activeTab, onEditDeviceName }) => (
  <header className="bg-white border-b border-gray-200 sticky top-0 z-50 shadow-sm safe-area-inset-top">
    <div className="flex justify-between items-center px-4 py-2 max-w-7xl mx-auto h-16">
      <div className="flex items-center gap-3 cursor-pointer" onClick={() => setTab('dashboard')}>
        <img src="/logo.png" alt="KSF Logo" className="h-12 w-auto object-contain flex-shrink-0" />
        <div className="hidden sm:block leading-tight">
          <h1 className="text-lg font-bold text-gray-900">KSF Non-Woven</h1>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider">Inventory System</p>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <div className="text-right hidden md:block">
            {isGuest ? (<div className="flex items-center gap-1 text-xs font-bold text-orange-600 bg-orange-50 px-2 py-1 rounded-full">👀 View Only</div>) : (
                <>
                    <div className="flex items-center justify-end gap-1 group cursor-pointer" onClick={onEditDeviceName} title="Edit Device Name">
                        <div className="text-xs font-bold text-gray-900 group-hover:text-blue-600 transition-colors">{deviceName}</div>
                        <span>✏️</span>
                    </div>
                    <div className="text-[10px] text-gray-500">{user?.email}</div>
                </>
            )}
        </div>
        <button onClick={onLogout} className="p-2 text-gray-600 hover:bg-red-50 hover:text-red-600 rounded-lg transition-colors">Log Out</button>
      </div>
    </div>
    <nav className="flex gap-1 px-2 overflow-x-auto no-scrollbar max-w-7xl mx-auto border-t border-gray-100 md:border-none">
      {[{ id: 'dashboard', label: '📊 Dash' }, !isGuest && { id: 'entry', label: '➕ New' }, { id: 'stock', label: '📦 Stock' }, { id: 'dispatch', label: '🚚 Disp' }, { id: 'history', label: '🕒 Hist' }, { id: 'materials', label: '🧱 Mat' }].filter(Boolean).map(tab => (
        <button key={tab.id} onClick={() => setTab(tab.id)} className={`flex flex-col md:flex-row items-center justify-center gap-1 md:gap-2 px-3 py-3 md:py-3 rounded-t-lg text-[10px] md:text-sm font-medium transition-all min-w-[65px] flex-1 md:flex-none border-b-2 ${activeTab === tab.id ? 'border-blue-600 text-blue-600 bg-blue-50/50' : 'border-transparent text-gray-500 hover:text-gray-900 hover:bg-gray-50'}`}>
          <span>{tab.label}</span>
        </button>
      ))}
    </nav>
  </header>
));

const DeviceNameModal = ({ onSave, initialName, onClose }) => {
    const [name, setName] = useState(initialName || '');
    return (
        <div className="fixed inset-0 bg-slate-900/95 z-[200] flex items-center justify-center p-6 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white p-8 rounded-2xl max-w-md w-full text-center shadow-2xl relative">
                {onClose && <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600">✕</button>}
                <h2 className="text-2xl font-bold mb-2">Name this Device</h2>
                <p className="text-gray-500 mb-6 text-sm">This name will appear in the activity logs.<br/>e.g., "Production Line 1"</p>
                <input className="w-full border-2 border-gray-300 p-4 rounded-xl text-lg mb-4 text-center focus:border-blue-600 outline-none font-bold text-gray-800" placeholder="Enter Device Name" value={name} onChange={e => setName(e.target.value)} autoFocus />
                <button disabled={!name} onClick={() => onSave(name)} className="w-full bg-blue-600 text-white py-4 rounded-xl font-bold text-lg disabled:opacity-50 hover:bg-blue-700 transition-colors shadow-lg shadow-blue-200">Save Device Name</button>
            </div>
        </div>
    );
};

const BarcodeScanner = ({ onScan, onClose }) => {
    const scannerRef = useRef(null);
    useEffect(() => {
        const initTimer = setTimeout(() => {
            if (scannerRef.current) return;
            const html5QrCode = new Html5Qrcode("reader");
            scannerRef.current = html5QrCode;
            const config = { fps: 15, qrbox: { width: 250, height: 250 }, aspectRatio: 1.0, formatsToSupport: [ Html5QrcodeSupportedFormats.CODE_128 ] };
            html5QrCode.start({ facingMode: "environment" }, config, (decodedText) => onScan(decodedText), () => {}).catch(err => console.log("Camera Error", err));
        }, 300);
        return () => { 
            if (scannerRef.current) { 
                try { scannerRef.current.stop().then(() => scannerRef.current.clear()); } catch(e) {} 
            } 
        };
    }, [onScan]);

    return (
        <div className="fixed inset-0 bg-black/90 z-[100] flex flex-col items-center justify-center p-4">
            <div className="w-full max-w-sm bg-white rounded-xl overflow-hidden p-4">
                 <h3 className="text-center font-bold mb-2">Scan Roll Barcode</h3>
                 <div id="reader" className="w-full bg-black min-h-[300px]"></div>
                 <button onClick={onClose} className="w-full mt-4 bg-red-100 text-red-600 py-3 rounded-lg font-bold">Close Scanner</button>
            </div>
        </div>
    );
};

const LabelPrint = ({ data, onClose }) => {
  const savedDesign = safeJSONParse('ksf_label_design_v15', {});
  const savedLabels = safeJSONParse('ksf_label_labels_v15', {});
  const [showLogo, setShowLogo] = useState(savedDesign.showLogo ?? true);
  const [labelSize, setLabelSize] = useState(savedDesign.labelSize || '4in-3in');
  const [baseFontSize, setBaseFontSize] = useState(savedDesign.baseFontSize || 11); 
  const [logoSize, setLogoSize] = useState(savedDesign.logoSize || 45);
  const [barcodeScale, setBarcodeScale] = useState(savedDesign.barcodeScale || 40);
  const [content, setContent] = useState({
      qualityLabel: savedLabels.qualityLabel || 'Quality:', 
      qualityVal: data?.quality || '', 
      gsmLabel: savedLabels.gsmLabel || 'GSM:', 
      gsmVal: data?.gsm || '',
      colorLabel: savedLabels.colorLabel || 'Color:', 
      colorVal: data?.color || '',
      widthLabel: savedLabels.widthLabel || 'Width:', 
      widthVal: data?.width_inches ? `${data.width_inches}"` : '',
      lengthLabel: savedLabels.lengthLabel || 'Length:', 
      lengthVal: data?.length_meters ? `${data.length_meters}m` : '',
      netLabel: savedLabels.netLabel || 'Net Wt:', 
      netVal: data?.net_weight ? `${data.net_weight}kg` : '',
      grossLabel: savedLabels.grossLabel || 'Gross Wt:', 
      grossVal: data?.gross_weight ? `${data.gross_weight}kg` : ''
  });
  const canvasRef = useRef(null);
  useEffect(() => {
      localStorage.setItem('ksf_label_design_v15', JSON.stringify({ showLogo, labelSize, baseFontSize, logoSize, barcodeScale }));
      const labelsOnly = { 
          qualityLabel: content.qualityLabel, gsmLabel: content.gsmLabel, colorLabel: content.colorLabel, 
          widthLabel: content.widthLabel, lengthLabel: content.lengthLabel, netLabel: content.netLabel, grossLabel: content.grossLabel 
      };
      localStorage.setItem('ksf_label_labels_v15', JSON.stringify(labelsOnly));
  }, [showLogo, labelSize, baseFontSize, logoSize, barcodeScale, content]);
  useEffect(() => {
      if (data && canvasRef.current) {
          try { JsBarcode(canvasRef.current, data.product_id, { format: "CODE128", width: 2, height: barcodeScale, displayValue: false, margin: 0 }); } catch (e) { console.error(e); }
      }
  }, [data, barcodeScale]);
  const handlePrint = () => window.print();
  const handleChange = (field, val) => setContent(prev => ({...prev, [field]: val}));
  if (!data) return null;
  const fontStyle = { fontFamily: "'Courier New', Courier, monospace", lineHeight: '1.1' };
  const inputStyle = { ...fontStyle, background: 'transparent', border: 'none', outline: 'none', padding: 0, margin: 0, color: '#000', fontSize: `${baseFontSize}px` };
  const labelStyle = { ...inputStyle, fontWeight: '900', width: 'auto', marginRight: '4px' };
  const valueStyle = { ...inputStyle, fontWeight: '600', flex: 1, minWidth: 0 };
  const printContainerStyle = { width: '4in', height: '3in', backgroundColor: 'white', overflow: 'hidden', display: 'flex', flexDirection: 'column', padding: '0.1in', border: '3px solid black', boxSizing: 'border-box' };
  const rowStyle = { display: 'flex', justifyContent: 'space-between', marginBottom: '2px', alignItems: 'baseline' };
  const colStyle = { display: 'flex', width: '48%', alignItems: 'baseline', whiteSpace: 'nowrap' };
  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-[100] p-4 overflow-y-auto">
      <style>{`@media print { @page { size: 4in 3in; margin: 0; } body * { visibility: hidden; } #print-wrapper, #print-wrapper * { visibility: visible; } #print-wrapper { position: absolute; top: 0; left: 0; margin: 0; border: none !important; padding: 0 !important; width: 4in !important; height: 3in !important; } #print-controls { display: none !important; } }`}</style>
      <div className="bg-white p-4 rounded-xl max-w-lg w-full flex flex-col items-center animate-in fade-in zoom-in-95 my-auto">
        <div id="print-controls" className="w-full mb-4 space-y-3 bg-slate-50 p-3 rounded-lg border border-slate-200">
             <div className="flex justify-between items-center"><span className="text-xs font-bold text-slate-500 uppercase">⚙️ Settings</span><div className="text-xs font-bold bg-slate-200 px-2 py-1 rounded">4" x 3" Label</div></div>
             <div className="flex items-center justify-between border-t border-slate-200 pt-2"><span className="text-xs font-bold text-slate-500">Font Size</span><div className="flex gap-1 bg-white p-1 rounded border"><button onClick={() => setBaseFontSize(f => Math.max(8, f-1))} className="p-1 hover:bg-slate-100 rounded font-bold">-</button><span className="text-xs font-bold w-6 text-center pt-0.5">{baseFontSize}</span><button onClick={() => setBaseFontSize(f => Math.min(24, f+1))} className="p-1 hover:bg-slate-100 rounded font-bold">+</button></div></div>
            <div className="grid grid-cols-2 gap-4 pt-1 border-t border-slate-200"><div><label className="text-[10px] font-bold text-slate-400 block mb-1">Logo</label><input type="range" min="20" max="80" value={logoSize} onChange={e => setLogoSize(Number(e.target.value))} className="w-full h-1 bg-slate-300 rounded-lg appearance-none cursor-pointer"/></div><div><label className="text-[10px] font-bold text-slate-400 block mb-1">Barcode</label><input type="range" min="20" max="80" value={barcodeScale} onChange={e => setBarcodeScale(Number(e.target.value))} className="w-full h-1 bg-slate-300 rounded-lg appearance-none cursor-pointer"/></div></div>
             <div className="flex items-center justify-between border-t border-slate-200 pt-2"><span className="text-xs font-bold text-slate-500">Show Logo</span><button onClick={() => setShowLogo(!showLogo)} className={`w-8 h-4 rounded-full transition-colors ${showLogo ? 'bg-green-500' : 'bg-slate-300'}`}></button></div>
        </div>
        <div id="print-wrapper" className="flex items-center justify-center bg-gray-200 p-4 rounded-lg border border-dashed border-gray-400 overflow-auto w-full">
            <div id="print-area" style={printContainerStyle}>
                <div className="w-full flex justify-center pb-1" style={{minHeight: showLogo ? 'auto' : '10px'}}>{showLogo && <img src="/logo.png" style={{ height: `${logoSize}px`, objectFit: 'contain' }} alt="Logo" />}</div>
                <div style={{ width: '100%', borderTop: '2px solid black', marginBottom: '4px' }}></div>
                <div style={rowStyle}><div style={colStyle}><input style={labelStyle} value={content.qualityLabel} onChange={e=>handleChange('qualityLabel',e.target.value)}/><input style={valueStyle} value={content.qualityVal} onChange={e=>handleChange('qualityVal',e.target.value)}/></div><div style={colStyle}><input style={labelStyle} value={content.gsmLabel} onChange={e=>handleChange('gsmLabel',e.target.value)}/><input style={valueStyle} value={content.gsmVal} onChange={e=>handleChange('gsmVal',e.target.value)}/></div></div>
                <div style={rowStyle}><div style={colStyle}><input style={labelStyle} value={content.colorLabel} onChange={e=>handleChange('colorLabel',e.target.value)}/><input style={valueStyle} value={content.colorVal} onChange={e=>handleChange('colorVal',e.target.value)}/></div><div style={colStyle}><input style={labelStyle} value={content.widthLabel} onChange={e=>handleChange('widthLabel',e.target.value)}/><input style={valueStyle} value={content.widthVal} onChange={e=>handleChange('widthVal',e.target.value)}/></div></div>
                <div style={rowStyle}><div style={colStyle}><input style={labelStyle} value={content.lengthLabel} onChange={e=>handleChange('lengthLabel',e.target.value)}/><input style={valueStyle} value={content.lengthVal} onChange={e=>handleChange('lengthVal',e.target.value)}/></div><div style={colStyle}><input style={labelStyle} value={content.netLabel} onChange={e=>handleChange('netLabel',e.target.value)}/><input style={valueStyle} value={content.netVal} onChange={e=>handleChange('netVal',e.target.value)}/></div></div>
                <div style={{...rowStyle, justifyContent: 'flex-start', marginTop: '2px'}}><input style={{...labelStyle, width: 'auto'}} value={content.grossLabel} onChange={e=>handleChange('grossLabel',e.target.value)}/><input style={valueStyle} value={content.grossVal} onChange={e=>handleChange('grossVal',e.target.value)}/></div>
                <div className="w-full flex flex-col items-center justify-end mt-auto pt-1"><canvas ref={canvasRef} style={{ maxWidth: '100%', height: 'auto' }}></canvas><div style={{ fontWeight: 'bold', fontSize: `${baseFontSize * 1.2}px`, marginTop: '1px', ...fontStyle }}>{data.product_id}</div></div>
            </div>
        </div>
        <div id="print-controls" className="flex gap-3 w-full mt-4"><button onClick={handlePrint} className="flex-1 bg-blue-600 text-white py-3 rounded-xl flex items-center justify-center gap-2 font-bold shadow-lg shadow-blue-200 hover:bg-blue-700 transition-colors">🖨️ Print Label</button><button onClick={onClose} className="flex-1 bg-gray-100 text-gray-600 py-3 rounded-xl font-bold hover:bg-gray-200 transition-colors">Close</button></div>
      </div>
    </div>
  );
};

const NewProductView = ({ formData, setFormData, onSubmit }) => (
    <div className="bg-white p-4 rounded-lg shadow border mt-2">
      <h2 className="text-lg font-bold mb-4 flex items-center gap-2 text-gray-800 border-b pb-2">➕ New Roll Entry</h2>
      <form onSubmit={onSubmit} className="grid grid-cols-2 gap-3">
        <div className="col-span-2"><label className="text-xs font-bold text-gray-500 uppercase">Customer</label><input required className="w-full border p-2 rounded" value={formData.customer_name} onChange={e => setFormData({...formData, customer_name: e.target.value})} /></div>
        <div><label className="text-xs font-bold text-gray-500 uppercase">Quality</label><select required className="w-full border p-2 rounded" value={formData.quality} onChange={e => setFormData({...formData, quality: e.target.value})}><option value="">Select...</option>{QUALITIES.map(q => <option key={q} value={q}>{q}</option>)}</select></div>
        <div><label className="text-xs font-bold text-gray-500 uppercase">Color</label><select required className="w-full border p-2 rounded" value={formData.color} onChange={e => setFormData({...formData, color: e.target.value})}><option value="">Select...</option>{COLORS.map(c => <option key={c} value={c}>{c}</option>)}</select></div>
        <div className="col-span-2 grid grid-cols-3 gap-3">
            <div><label className="text-xs font-bold text-gray-500 uppercase">GSM</label><input type="number" className="w-full border p-2 rounded" value={formData.gsm} onChange={e => setFormData({...formData, gsm: e.target.value})} /></div>
            <div><label className="text-xs font-bold text-gray-500 uppercase">Width</label><input type="number" className="w-full border p-2 rounded" value={formData.width_inches} onChange={e => setFormData({...formData, width_inches: e.target.value})} /></div>
            <div><label className="text-xs font-bold text-gray-500 uppercase">Length</label><input type="number" className="w-full border p-2 rounded" value={formData.length_meters} onChange={e => setFormData({...formData, length_meters: e.target.value})} /></div>
        </div>
        <div><label className="text-xs font-bold text-gray-500 uppercase">Net Kg</label><input type="number" className="w-full border p-2 rounded font-bold" value={formData.net_weight} onChange={e => setFormData({...formData, net_weight: e.target.value})} /></div>
        <div><label className="text-xs font-bold text-gray-500 uppercase">Gross Kg</label><input type="number" className="w-full border p-2 rounded" value={formData.gross_weight} onChange={e => setFormData({...formData, gross_weight: e.target.value})} /></div>
        <button type="submit" className="col-span-2 bg-blue-600 text-white p-3 rounded font-bold mt-2">Save & Print</button>
      </form>
    </div>
);

const EditModal = ({ roll, isGuest, onClose, onSave, onDelete }) => {
    const [editData, setEditData] = useState({ ...roll });
    const handleDelete = () => { if(window.confirm("Delete this roll?")) { onDelete(roll.id); onClose(); } };
    const handleReturnToStock = () => { if(window.confirm("Undo Dispatch?")) { onSave({ ...editData, status: 'in_stock', dispatched_at: null }); } };

    return (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-[100] p-4">
            <div className="bg-white p-6 rounded-lg w-full max-w-lg">
                <div className="flex justify-between mb-4"><h2 className="font-bold text-lg">Edit Roll {roll.product_id}</h2><button onClick={onClose}>✕</button></div>
                <div className="grid grid-cols-2 gap-3 mb-4">
                    <div className="col-span-2"><label className="text-xs font-bold">Customer</label><input disabled={isGuest} className="w-full border p-2 rounded" value={editData.customer_name || ''} onChange={e => setEditData({...editData, customer_name: e.target.value})} /></div>
                    <div><label className="text-xs font-bold">Net Kg</label><input disabled={isGuest} type="number" className="w-full border p-2 rounded" value={editData.net_weight} onChange={e => setEditData({...editData, net_weight: e.target.value})} /></div>
                    <div><label className="text-xs font-bold">Gross Kg</label><input disabled={isGuest} type="number" className="w-full border p-2 rounded" value={editData.gross_weight} onChange={e => setEditData({...editData, gross_weight: e.target.value})} /></div>
                </div>
                {!isGuest && (
                    <div className="flex flex-col gap-2">
                        {roll.status === 'dispatched' && <button onClick={handleReturnToStock} className="bg-orange-100 text-orange-700 p-3 rounded font-bold flex items-center justify-center gap-2">↺ Return to Stock</button>}
                        <button onClick={() => onSave(editData)} className="bg-blue-600 text-white p-3 rounded font-bold">Save Changes</button>
                        <button onClick={handleDelete} className="bg-white border border-red-500 text-red-500 p-3 rounded font-bold">Delete Roll</button>
                    </div>
                )}
            </div>
        </div>
    );
};

const StockView = ({ rolls = [], onPrint, onExport, onSelectRoll }) => {
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState({ color: 'All', quality: 'All', gsm: 'All' });
  const uniqueColors = useMemo(() => ['All', ...new Set((rolls || []).map(r => r.color).filter(Boolean))], [rolls]);
  const uniqueQualities = useMemo(() => ['All', ...new Set((rolls || []).map(r => r.quality).filter(Boolean))], [rolls]);
  const uniqueGSM = useMemo(() => ['All', ...new Set((rolls || []).map(r => r.gsm).filter(Boolean))], [rolls]);
  const filtered = useMemo(() => {
      if (!rolls) return [];
      return rolls.filter(r => {
          if (!r || r.status !== 'in_stock') return false;
          if (filters.color !== 'All' && r.color !== filters.color) return false;
          if (filters.quality !== 'All' && r.quality !== filters.quality) return false;
          if (filters.gsm !== 'All' && r.gsm != filters.gsm) return false;
          if (!search.trim()) return true;
          const terms = search.toLowerCase().split(' ').filter(Boolean);
          return terms.every(term => ((r.product_id||'').toLowerCase().includes(term) || (r.customer_name||'').toLowerCase().includes(term) || (r.quality||'').toLowerCase().includes(term) || (r.color||'').toLowerCase().includes(term) || String(r.gsm||'').includes(term) || String(r.width_inches||'').includes(term) || String(r.net_weight||'').includes(term)));
      });
  }, [rolls, search, filters]);
  const totalWeight = useMemo(() => filtered.reduce((sum, r) => sum + (parseFloat(r.net_weight) || 0), 0), [filtered]);
  return (
      <div className="space-y-4 h-full flex flex-col">
          <div className="sticky top-0 bg-slate-50 z-10 pb-2 space-y-2">
              <div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input className="w-full pl-10 p-2.5 bg-white border-gray-200 border rounded-xl shadow-sm focus:ring-2 focus:ring-blue-500 outline-none" placeholder="Search (Cust 38 60...)" value={search} onChange={e => setSearch(e.target.value)} /></div><button onClick={onExport} className="bg-white border border-green-200 text-green-700 p-2.5 rounded-xl shadow-sm"><Download size={20} /></button></div>
              <div className="flex gap-2 overflow-x-auto no-scrollbar"><select className="bg-white border p-2 rounded-lg text-xs font-bold text-gray-600 min-w-[100px]" value={filters.color} onChange={e => setFilters({...filters, color: e.target.value})}>{uniqueColors.map(c => <option key={c} value={c}>Color: {c}</option>)}</select><select className="bg-white border p-2 rounded-lg text-xs font-bold text-gray-600 min-w-[100px]" value={filters.quality} onChange={e => setFilters({...filters, quality: e.target.value})}>{uniqueQualities.map(q => <option key={q} value={q}>Qual: {q}</option>)}</select><select className="bg-white border p-2 rounded-lg text-xs font-bold text-gray-600 min-w-[80px]" value={filters.gsm} onChange={e => setFilters({...filters, gsm: e.target.value})}>{uniqueGSM.map(g => <option key={g} value={g}>GSM: {g}</option>)}</select></div>
              <div className="bg-blue-600 text-white p-3 rounded-xl flex justify-between items-center shadow-sm shadow-blue-200"><div className="text-xs font-bold opacity-80 uppercase">Filtered Stock</div><div className="flex items-center gap-4"><div className="text-right"><div className="text-xs opacity-70">Count</div><div className="font-bold">{filtered.length}</div></div><div className="text-right"><div className="text-xs opacity-70">Total Kg</div><div className="font-bold text-lg">{totalWeight.toLocaleString()}</div></div></div></div>
          </div>
          <div className="flex-1 overflow-y-auto pb-20">{filtered.map(r => (<div key={r.id} onClick={() => onSelectRoll(r)} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 mb-3 flex justify-between items-center active:bg-blue-50 transition-colors cursor-pointer"><div><div className="flex flex-wrap items-center gap-2 mb-1"><span className="font-mono font-bold text-xs text-blue-600 bg-blue-50 px-2 py-0.5 rounded">{r.product_id}</span><span className="text-xs font-extrabold text-gray-800 uppercase tracking-wide">{r.customer_name}</span></div><div className="text-gray-900 font-medium text-sm">{r.quality} • {r.color} • {r.width_inches}" • {r.gsm} GSM</div><div className="text-sm text-gray-500 mt-1">Wt: <strong>{r.net_weight}kg</strong> • Len: {r.length_meters}m</div></div><button onClick={(e) => { e.stopPropagation(); onPrint(r); }} className="p-3 text-gray-400 hover:text-blue-600 bg-gray-50 rounded-lg"><Printer size={20}/></button></div>))}{filtered.length === 0 && <div className="text-center text-gray-400 py-10">No Stock Found</div>}</div>
      </div>
  );
};

const HistoryView = ({ rolls = [], onSelectRoll, onExport, onUpdateRoll }) => {
    const safeRolls = Array.isArray(rolls) ? rolls : [];
    const history = useMemo(() => safeRolls.filter(r => r.status === 'dispatched').sort((a, b) => new Date(b.dispatched_at) - new Date(a.dispatched_at)), [safeRolls]);
    const totalDispatchedWeight = history.reduce((acc, curr) => acc + parseFloat(curr.net_weight || 0), 0);
    const handleReturn = async (roll) => {
        if(window.confirm(`Return ${roll.product_id} to stock?`)) { await onUpdateRoll({ ...roll, status: 'in_stock', dispatched_at: null }); }
    };
    return (
        <div className="space-y-4 h-full flex flex-col"><div className="bg-slate-800 text-white p-5 rounded-xl shadow-md relative"><button onClick={() => onExport(history)} className="absolute top-4 right-4 bg-white/10 p-2 rounded-lg text-white hover:bg-white/20"><Download size={18}/></button><div className="flex items-center gap-2 mb-2 text-slate-300 text-sm uppercase font-bold tracking-wider"><Clock size={16}/> Dispatch Log</div><div className="flex justify-between items-end"><div><div className="text-3xl font-black">{history.length}</div><div className="text-xs text-slate-400">Rolls Sent</div></div><div className="text-right"><div className="text-3xl font-black text-green-400">{totalDispatchedWeight.toLocaleString()}</div><div className="text-xs text-slate-400">Total Kg</div></div></div></div><div className="flex-1 overflow-y-auto pb-20">{history.map(r => (<div key={r.id} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 mb-3 relative flex justify-between items-center hover:bg-gray-50"><div onClick={() => onSelectRoll(r)} className="cursor-pointer flex-1"><div className="text-xs font-bold text-gray-400 mb-1">{new Date(r.dispatched_at).toLocaleDateString()}</div><div className="mb-1"><span className="font-mono font-bold text-xs text-slate-500 bg-slate-100 px-2 py-0.5 rounded">{r.product_id}</span></div><div className="text-sm font-bold text-gray-900">{r.customer_name || 'Unknown'}</div><div className="text-xs text-gray-500">{r.net_weight} kg • {r.quality}</div></div><button onClick={(e) => { e.stopPropagation(); handleReturn(r); }} className="p-3 bg-orange-50 text-orange-600 rounded-lg hover:bg-orange-100 border border-orange-100 ml-2" title="Return to Stock">↺</button></div>))}</div></div>
    );
};

const DispatchView = ({ rolls, isGuest, deviceName, onDispatch, onUpdateRoll }) => {
    const [scanId, setScanId] = useState('');
    const [foundRoll, setFoundRoll] = useState(null);
    const [editedRoll, setEditedRoll] = useState(null);
    const [showScanner, setShowScanner] = useState(false);
    const [sessionList, setSessionList] = useState(() => safeJSONParse('ksf_dispatch_list_v15', []));
    const [customerName, setCustomerName] = useState(() => localStorage.getItem('ksf_dispatch_customer_v15') || '');
    const [vehicleNo, setVehicleNo] = useState(() => localStorage.getItem('ksf_dispatch_vehicle_v15') || '');
    useEffect(() => {
        localStorage.setItem('ksf_dispatch_list_v15', JSON.stringify(sessionList));
        localStorage.setItem('ksf_dispatch_customer_v15', customerName);
        localStorage.setItem('ksf_dispatch_vehicle_v15', vehicleNo);
    }, [sessionList, customerName, vehicleNo]);
    const handleSearch = useCallback((idOverride) => {
        const query = idOverride || scanId;
        const roll = (rolls || []).find(r => r.product_id === query && r.status === 'in_stock');
        if (roll) { setFoundRoll(roll); setEditedRoll({ ...roll }); setScanId(query); setShowScanner(false); } 
        else { alert('Roll not found or already dispatched.'); }
    }, [rolls, scanId]);
    const handleConfirmDispatch = async () => {
        if (editedRoll.net_weight !== foundRoll.net_weight || editedRoll.customer_name !== foundRoll.customer_name) { await onUpdateRoll(editedRoll); }
        onDispatch(editedRoll.id);
        const newItem = { ...editedRoll, added_at: new Date().toISOString() };
        setSessionList(prev => [newItem, ...prev]);
        setFoundRoll(null);
        setEditedRoll(null);
        setScanId('');
    };
    const handleRemoveFromList = async (itemToRemove) => {
        if(!window.confirm(`Remove ${itemToRemove.product_id} from this list? It will be marked as 'In Stock' again.`)) return;
        try {
            await onUpdateRoll({ ...itemToRemove, status: 'in_stock', dispatched_at: null });
            setSessionList(prev => prev.filter(item => item.id !== itemToRemove.id));
            alert("Item returned to stock.");
        } catch(e) {
            alert("Error removing item: " + e.message);
        }
    };
    const handlePrintChallan = () => {
        if(!customerName) return alert("Please enter a Customer Name for the List!");
        if(!vehicleNo) return alert("Please enter Vehicle Number!");
        if(sessionList.length === 0) return alert("List is empty!");
        if(generateChallan(sessionList, { buyer: customerName, vehicle: vehicleNo, device: deviceName })) {
             if(window.confirm("Gate Pass Generated. Start a new batch? (This clears the current list)")) { 
                setSessionList([]); setCustomerName(''); setVehicleNo(''); 
            }
        }
    };
    const totalWeight = sessionList.reduce((acc, r) => acc + parseFloat(r.net_weight || 0), 0);
    return (
        <div className="max-w-xl mx-auto space-y-4 pb-20">
            {showScanner && <BarcodeScanner onScan={(text) => { if(text) handleSearch(text); else setShowScanner(false); }} onClose={() => setShowScanner(false)} />}
            <div className="bg-blue-600 p-4 rounded-xl text-white shadow-lg shadow-blue-200"><h3 className="font-bold text-sm opacity-80 uppercase mb-2 flex items-center gap-2"><FileText size={16}/> Dispatch Manifest</h3><input className="w-full bg-blue-700/50 border border-blue-500 rounded p-2 text-white placeholder-blue-300 font-bold mb-2 outline-none focus:bg-blue-700" placeholder="Customer Name (e.g. Supreme Pack)" value={customerName} onChange={e => setCustomerName(e.target.value)} /><input className="w-full bg-blue-700/50 border border-blue-500 rounded p-2 text-white placeholder-blue-300 text-sm outline-none focus:bg-blue-700" placeholder="Vehicle No (e.g. UP 27 AA 0000)" value={vehicleNo} onChange={e => setVehicleNo(e.target.value)} /><div className="flex justify-between items-end mt-3 border-t border-blue-500 pt-2"><div><div className="text-xs opacity-70">Date</div><div className="font-bold text-sm">{new Date().toLocaleDateString()}</div></div><div className="text-right"><div className="text-xs opacity-70">Total List Weight</div><div className="font-black text-2xl">{totalWeight.toLocaleString()} <span className="text-sm font-normal">kg</span></div></div></div></div>
            {!foundRoll && (<div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 text-center"><div className="mb-4"><h2 className="text-lg font-bold mb-2 text-gray-800">Add to List</h2><input className="w-full bg-gray-50 border-2 border-gray-200 p-4 text-center text-xl font-mono tracking-widest rounded-xl focus:border-blue-500 focus:bg-white outline-none transition-all" placeholder="Scan Barcode" value={scanId} onChange={(e) => setScanId(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleSearch()}/></div><div className="grid grid-cols-2 gap-3"><button onClick={() => setShowScanner(true)} className="bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2"><Camera size={20}/> Camera</button><button onClick={() => handleSearch()} className="bg-gray-900 text-white py-3 rounded-xl font-bold">Search</button></div></div>)}
            {foundRoll && editedRoll && (<div className="bg-green-50 border border-green-200 p-5 rounded-xl animate-in fade-in slide-in-from-bottom-4"><h3 className="font-bold text-green-900 mb-4 flex items-center gap-2"><Package size={20}/> Confirm Item</h3><div className="bg-white/70 p-4 rounded-lg grid grid-cols-2 gap-3 text-sm mb-4 border border-green-100"><div className="col-span-2 text-center border-b pb-2 mb-1"><span className="text-gray-500 text-xs">ID:</span> <span className="font-mono font-bold text-lg">{foundRoll.product_id}</span></div><div><label className="text-xs text-gray-500 font-bold uppercase">Customer</label><input className="w-full border p-2 rounded bg-white" value={editedRoll.customer_name || ''} onChange={e => setEditedRoll({...editedRoll, customer_name: e.target.value})} /></div><div><label className="text-xs text-gray-500 font-bold uppercase">Weight (Kg)</label><input type="number" className="w-full border p-2 rounded bg-white font-bold text-green-800" value={editedRoll.net_weight} onChange={e => setEditedRoll({...editedRoll, net_weight: e.target.value})} /></div><div><label className="text-xs text-gray-500 font-bold uppercase">Quality</label><input className="w-full border p-2 rounded bg-white" value={editedRoll.quality} onChange={e => setEditedRoll({...editedRoll, quality: e.target.value})} /></div><div><label className="text-xs text-gray-500 font-bold uppercase">Color</label><input className="w-full border p-2 rounded bg-white" value={editedRoll.color} onChange={e => setEditedRoll({...editedRoll, color: e.target.value})} /></div></div>{isGuest ? (<div className="bg-orange-100 text-orange-700 p-3 rounded-lg font-bold text-center">Login to Dispatch</div>) : (<div className="flex gap-2"><button onClick={() => { setFoundRoll(null); setScanId(''); }} className="flex-1 bg-gray-200 text-gray-700 py-3 rounded-xl font-bold">Cancel</button><button onClick={handleConfirmDispatch} className="flex-[2] bg-green-600 hover:bg-green-700 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2">✅ Add to List</button></div>)}</div>)}
            {sessionList.length > 0 && (<div className="space-y-2"><div className="flex justify-between items-center px-2"><h4 className="font-bold text-gray-500 text-xs uppercase">Items in this Batch ({sessionList.length})</h4></div>{sessionList.map((item, idx) => (<div key={idx} className="bg-white p-3 rounded-lg border border-gray-100 flex justify-between items-center shadow-sm"><div><div className="font-mono font-bold text-sm text-blue-600">{item.product_id}</div><div className="text-xs text-gray-500">{item.quality} • {item.width_inches}" • {item.color}</div></div><div className="flex items-center gap-3"><div className="text-right"><div className="font-bold text-gray-900">{item.net_weight} kg</div></div><button onClick={() => handleRemoveFromList(item)} className="p-2 text-red-400 hover:bg-red-50 hover:text-red-600 rounded-lg transition-colors"><Trash2 size={16}/></button></div></div>))}<button onClick={handlePrintChallan} className="w-full mt-4 bg-gray-900 text-white py-4 rounded-xl font-bold flex items-center justify-center gap-2 shadow-xl"><Printer size={20}/> Generate Gate Pass PDF</button></div>)}
        </div>
    );
};

const MaterialsView = ({ materials, isGuest, onUpdate, onAdd }) => { const handleUpdate = (id, type) => { const qty = prompt(`Enter quantity to ${type} (Kg):`); if (qty && !isNaN(qty)) onUpdate(id, qty, type === 'add'); }; const handleAdd = () => { const name = prompt("Enter Material Name:"); if(name) onAdd(name); }; return (<div className="pb-20">{!isGuest && <button onClick={handleAdd} className="w-full bg-white border-2 border-dashed border-gray-300 text-gray-500 py-3 rounded-xl font-bold mb-4 hover:border-blue-400 hover:text-blue-500 transition-colors">+ Add New Material</button>}<div className="grid grid-cols-1 gap-3">{materials.map(m => (<div key={m.id} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between"><div><h3 className="font-bold text-gray-700 text-sm">{m.name}</h3><div className="text-2xl font-black text-gray-900">{m.stock_quantity} <span className="text-xs font-medium text-gray-400">{m.unit}</span></div></div>{!isGuest && <div className="flex gap-2"><button onClick={() => handleUpdate(m.id, 'issue')} className="w-10 h-10 flex items-center justify-center bg-red-50 text-red-600 rounded-lg font-bold border border-red-100">-</button><button onClick={() => handleUpdate(m.id, 'add')} className="w-10 h-10 flex items-center justify-center bg-green-50 text-green-600 rounded-lg font-bold border border-green-100">+</button></div>}</div>))}</div></div>); };

// --- MAIN APP ---
export default function App() {
  const [user, setUser] = useState(null);
  const [isGuest, setIsGuest] = useState(false);
  const [deviceName, setDeviceName] = useState(localStorage.getItem('ksf_device_name') || '');
  const [activeTab, setActiveTab] = useState('dashboard');
  const [loading, setLoading] = useState(false);
  const [rolls, setRolls] = useState([]);
  const [materials, setMaterials] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [editRoll, setEditRoll] = useState(null);
  const [isDeviceModalOpen, setDeviceModalOpen] = useState(false);
  const [formData, setFormData] = useState({ customer_name: '', quality: '', gsm: '', color: '', width_inches: '', length_meters: '', net_weight: '', gross_weight: '' });

  const fetchDataRef = useRef();

  const fetchData = useCallback(async (isBackground = false) => {
      try {
          if (!isBackground) setLoading(true);
          const r = await DataService.getStock();
          const m = await DataService.getRawMaterials();
          setRolls(r || []);
          setMaterials(m || []);
      } catch (e) { console.error(e); } 
      finally { if (!isBackground) setLoading(false); }
  }, []);

  fetchDataRef.current = fetchData;

  useEffect(() => {
    const checkSession = async () => { 
        const { data: { session } } = await supabase.auth.getSession(); 
        if (session) { setUser(session.user); setIsGuest(false); fetchData(); } 
    };
    checkSession();
    
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => { 
        setUser(session?.user ?? null); 
        if (session && !user) { setIsGuest(false); fetchData(); } 
    });
    
    const interval = setInterval(() => { 
        if((user || isGuest) && fetchDataRef.current) fetchDataRef.current(true); 
    }, 10000);

    return () => { subscription.unsubscribe(); clearInterval(interval); };
  }, [fetchData]);

  // Force open modal if device name is missing on login
  useEffect(() => {
      if(user && !isGuest && !deviceName) {
          setDeviceModalOpen(true);
      }
  }, [user, isGuest, deviceName]);

  const handleLogin = async () => { await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } }); };
  const handleGuestEntry = () => { setIsGuest(true); fetchData(); };
  const handleLogout = async () => { await supabase.auth.signOut(); setUser(null); setIsGuest(false); setRolls([]); };
  
  const handleSaveDeviceName = (name) => { 
      localStorage.setItem('ksf_device_name', name); 
      setDeviceName(name); 
      setDeviceModalOpen(false); 
  };

  const handleSaveRoll = async (e) => { e.preventDefault(); const id = `KSF-${Math.floor(Math.random() * 1000000)}`; const newRoll = { ...formData, product_id: id, status: 'in_stock' }; try { await DataService.addRoll(newRoll, deviceName); setPrintData(newRoll); fetchData(); setFormData({ customer_name: '', quality: '', gsm: '', color: '', width_inches: '', length_meters: '', net_weight: '', gross_weight: '' }); } catch (err) { alert('Error: ' + err.message); } };
  const handleDispatch = useCallback(async (id) => { await DataService.updateRoll(id, { status: 'dispatched', dispatched_at: new Date() }, deviceName); fetchData(true); }, [deviceName, fetchData]);
  const handleDeleteRoll = async (id) => { await DataService.deleteRoll(id); fetchData(); };
  const handleEditRoll = useCallback(async (updates) => { await DataService.updateRoll(updates.id, updates, deviceName); setEditRoll(null); fetchData(true); }, [deviceName, fetchData]);
  const handleMaterialUpdate = async (id, qty, isAdd) => { await DataService.updateRawMaterial(id, qty, isAdd, deviceName); fetchData(); };
  const handleAddMaterial = async (name) => { await DataService.addRawMaterial(name); fetchData(); };
  const handleExport = (data = rolls) => { const ws = XLSX.utils.json_to_sheet(data); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Sheet1"); XLSX.writeFile(wb, "KSF_Data.xlsx"); };

  if (!user && !isGuest) { return (<div className="h-[100dvh] flex items-center justify-center bg-slate-50 p-6"><div className="bg-white p-8 rounded-2xl shadow-xl max-w-sm w-full text-center border border-gray-100"><img src="/logo.png" className="h-24 w-auto mx-auto mb-8 object-contain" alt="KSF" /><h1 className="text-2xl font-bold mb-2 text-gray-900">KSF Inventory</h1><p className="text-gray-500 mb-8">Manage your factory floor efficiently.</p><button onClick={handleLogin} className="w-full bg-blue-600 text-white py-3.5 rounded-xl font-bold mb-3 hover:bg-blue-700 active:scale-95 transition-all shadow-lg shadow-blue-200">Login with Google</button><button onClick={handleGuestEntry} className="w-full bg-white text-gray-700 py-3.5 rounded-xl font-bold hover:bg-gray-50 transition border border-gray-200 flex items-center justify-center gap-2"><Eye size={20}/> Monitor Only (Guest)</button></div></div>); }

  return (
    <div className="min-h-[100dvh] bg-slate-50 font-sans pb-10">
      <Header user={user} isGuest={isGuest} deviceName={deviceName} onLogout={handleLogout} setTab={setActiveTab} activeTab={activeTab} onEditDeviceName={() => setDeviceModalOpen(true)} />
      <main className="max-w-7xl mx-auto p-4 md:p-6 animate-in fade-in duration-500">
        {loading ? ( <div className="flex justify-center p-12"><div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div></div> ) : (
            <>
                {/* PASSING DEFAULT EMPTY ARRAYS TO PREVENT CRASHES */}
                {activeTab === 'dashboard' && <Dashboard rolls={rolls || []} materials={materials || []} />}
                {activeTab === 'entry' && <NewProductView formData={formData} setFormData={setFormData} onSubmit={handleSaveRoll} />}
                {activeTab === 'stock' && <StockView rolls={rolls || []} onPrint={setPrintData} onExport={() => handleExport(rolls)} onSelectRoll={setEditRoll} />}
                {activeTab === 'dispatch' && <DispatchView rolls={rolls || []} isGuest={isGuest} deviceName={deviceName} onDispatch={handleDispatch} onUpdateRoll={handleEditRoll} />}
                {activeTab === 'history' && <HistoryView rolls={rolls || []} onSelectRoll={setEditRoll} onExport={handleExport} onUpdateRoll={handleEditRoll} />}
                {activeTab === 'materials' && <MaterialsView materials={materials || []} isGuest={isGuest} onUpdate={handleMaterialUpdate} onAdd={handleAddMaterial} />}
            </>
        )}
      </main>
      
      {/* MODALS RENDERED HERE TO AVOID BLOCKING UI */}
      {isDeviceModalOpen && <DeviceNameModal onSave={handleSaveDeviceName} initialName={deviceName} onClose={() => setDeviceModalOpen(false)} />}
      {printData && <LabelPrint data={printData} onClose={() => setPrintData(null)} />}
      {editRoll && <EditModal roll={editRoll} isGuest={isGuest} onClose={() => setEditRoll(null)} onSave={handleEditRoll} onDelete={handleDeleteRoll} />}
    </div>
  );
}