import React, { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { createClient } from '@supabase/supabase-js';
import JsBarcode from 'jsbarcode';
import { Html5Qrcode, Html5QrcodeSupportedFormats } from 'html5-qrcode';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer, PieChart, Pie, Cell 
} from 'recharts';
import { 
  Package, Truck, Layers, LogOut, Printer, Search, 
  Download, Plus, Database, AlertCircle, Calendar, Clock, 
  Pencil, Trash2, X, Camera, Smartphone, Activity, Eye, FileText, Filter, RotateCcw, CheckCircle, ZoomIn, Edit3, Settings, Type, Bold, AlignLeft, AlignCenter, AlignRight, Minus, Plus as PlusIcon
} from 'lucide-react';
import { supabase } from './supabaseClient';

// --- CONSTANTS ---
const QUALITIES = ['Virgin', 'Fresh', 'Semi Fresh', 'Semi 2', 'Semi Star', 'UV Fabric'];
const COLORS = [
  'White', 'Ivory', 'Red', 'Maroon', 'Orange', 'Lemon Yellow', 'Golden Yellow', 
  'Bottle Green', 'Sea Green', 'Medical Blue', 'Royal Blue', 'Peacock Blue', 
  'Navy Blue', 'Beige', 'Coffee Brown', 'Gray', 'Black', 'Colour Change'
];

// --- DATA SERVICE ---
const DataService = {
  async getStock() {
    const { data, error } = await supabase.from('rolls').select('*').order('updated_at', { ascending: false });
    return error ? [] : data;
  },
  async addRoll(roll, deviceName) {
    const rollWithDevice = { ...roll, device_name: deviceName, updated_at: new Date() };
    const { data, error } = await supabase.from('rolls').insert([rollWithDevice]).select();
    if (error) throw error;
    return data[0];
  },
  async updateRoll(id, updates, deviceName) {
    const updatesWithDevice = { ...updates, device_name: deviceName, updated_at: new Date() };
    await supabase.from('rolls').update(updatesWithDevice).eq('id', id);
  },
  async deleteRoll(id) {
    await supabase.from('rolls').delete().eq('id', id);
  },
  async getRawMaterials() {
    const { data, error } = await supabase.from('raw_materials').select('*').order('name');
    return error ? [] : data;
  },
  async addRawMaterial(name) {
      const newMat = { name, stock_quantity: 0, unit: 'kg' };
      await supabase.from('raw_materials').insert([newMat]);
  },
  async updateRawMaterial(id, qty, isAddition, deviceName) {
    const { data } = await supabase.from('raw_materials').select('stock_quantity').eq('id', id).single();
    const currentQty = data ? parseFloat(data.stock_quantity) : 0;
    const newQty = currentQty + (isAddition ? parseFloat(qty) : -parseFloat(qty));
    await supabase.from('raw_materials').update({ stock_quantity: newQty, last_updated_by: deviceName }).eq('id', id);
  }
};

// --- HELPER: GENERATE PDF CHALLAN ---
const generateChallan = (rolls, details) => {
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.text("KSF NON WOVEN", 105, 20, null, null, "center");
    doc.setFontSize(12);
    doc.text("Shahjahanpur, Uttar Pradesh", 105, 28, null, null, "center");
    doc.text("DISPATCH CHALLAN / GATE PASS", 105, 36, null, null, "center");
    doc.setFontSize(10);
    doc.text(`Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, 50);
    doc.text(`Buyer: ${details.buyer}`, 14, 56);
    doc.text(`Vehicle No: ${details.vehicle}`, 14, 62);
    doc.text(`Generated By: ${details.device}`, 14, 68);
    const tableData = rolls.map((r, i) => [i + 1, r.product_id, r.quality, r.color, `${r.width_inches}"`, `${r.gsm}`, `${r.net_weight} kg`]);
    doc.autoTable({ startY: 75, head: [['#', 'Roll ID', 'Quality', 'Color', 'Size', 'GSM', 'Weight']], body: tableData, theme: 'grid', headStyles: { fillColor: [41, 128, 185] } });
    const totalWt = rolls.reduce((sum, r) => sum + Number(r.net_weight), 0);
    doc.setFontSize(12);
    doc.font = "helvetica";
    doc.setFont(undefined, 'bold');
    doc.text(`Total Rolls: ${rolls.length}`, 14, doc.lastAutoTable.finalY + 10);
    doc.text(`Total Weight: ${totalWt.toLocaleString()} kg`, 150, doc.lastAutoTable.finalY + 10);
    doc.setFont(undefined, 'normal');
    doc.text("Authorized Signatory", 14, doc.lastAutoTable.finalY + 30);
    doc.text("Receiver's Signature", 150, doc.lastAutoTable.finalY + 30);
    doc.save(`KSF_Challan_${Date.now()}.pdf`);
};

// --- COMPONENTS ---
const Header = React.memo(({ user, isGuest, deviceName, onLogout, setTab, activeTab, onEditDeviceName }) => (
  <header className="bg-white border-b border-gray-200 sticky top-0 z-50 shadow-sm safe-area-inset-top">
    <div className="flex justify-between items-center px-4 py-2 max-w-7xl mx-auto h-16">
      <div className="flex items-center gap-3 cursor-pointer" onClick={() => setTab('dashboard')}>
        <img src="/logo.png" alt="KSF Logo" className="h-12 w-auto object-contain flex-shrink-0" />
        <div className="hidden sm:block leading-tight">
          <h1 className="text-lg font-bold text-gray-900">KSF Non-Woven</h1>
          <p className="text-[10px] text-gray-500 uppercase tracking-wider">Inventory System</p>
        </div>
      </div>
      <div className="flex items-center gap-3">
        <div className="text-right hidden md:block">
            {isGuest ? (<div className="flex items-center gap-1 text-xs font-bold text-orange-600 bg-orange-50 px-2 py-1 rounded-full"><Eye size={12}/> View Only</div>) : (
                <>
                    <div className="flex items-center justify-end gap-1 group cursor-pointer" onClick={onEditDeviceName} title="Edit Device Name">
                        <div className="text-xs font-bold text-gray-900 group-hover:text-blue-600 transition-colors">{deviceName}</div>
                        <Edit3 size={10} className="text-gray-400 group-hover:text-blue-600"/>
                    </div>
                    <div className="text-[10px] text-gray-500">{user?.email}</div>
                </>
            )}
        </div>
        <button onClick={onLogout} className="p-2 text-gray-600 hover:bg-red-50 hover:text-red-600 rounded-lg transition-colors"><LogOut size={20} /></button>
      </div>
    </div>
    <nav className="flex gap-1 px-2 overflow-x-auto no-scrollbar max-w-7xl mx-auto border-t border-gray-100 md:border-none">
      {[{ id: 'dashboard', icon: Database, label: 'Dash' }, !isGuest && { id: 'entry', icon: Plus, label: 'New' }, { id: 'stock', icon: Package, label: 'Stock' }, { id: 'dispatch', icon: Truck, label: 'Dispatch' }, { id: 'history', icon: Calendar, label: 'History' }, { id: 'materials', icon: Layers, label: 'Materials' }].filter(Boolean).map(tab => (
        <button key={tab.id} onClick={() => setTab(tab.id)} className={`flex flex-col md:flex-row items-center justify-center gap-1 md:gap-2 px-3 py-3 md:py-3 rounded-t-lg text-[10px] md:text-sm font-medium transition-all min-w-[65px] flex-1 md:flex-none border-b-2 ${activeTab === tab.id ? 'border-blue-600 text-blue-600 bg-blue-50/50' : 'border-transparent text-gray-500 hover:text-gray-900 hover:bg-gray-50'}`}>
          <tab.icon size={18} className={activeTab === tab.id ? "text-blue-600" : "text-gray-400"} />
          <span>{tab.label}</span>
        </button>
      ))}
    </nav>
  </header>
));

const DeviceNameModal = ({ onSave, initialName, onClose }) => {
    const [name, setName] = useState(initialName || '');
    return (
        <div className="fixed inset-0 bg-slate-900/95 z-[200] flex items-center justify-center p-6 backdrop-blur-sm animate-in fade-in duration-200">
            <div className="bg-white p-8 rounded-2xl max-w-md w-full text-center shadow-2xl relative">
                {onClose && <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600"><X size={24}/></button>}
                <Smartphone size={48} className="mx-auto text-blue-600 mb-4"/>
                <h2 className="text-2xl font-bold mb-2">Name this Device</h2>
                <p className="text-gray-500 mb-6 text-sm">This name will appear in the activity logs.<br/>e.g., "Production Line 1", "Owner's iPhone"</p>
                <input className="w-full border-2 border-gray-300 p-4 rounded-xl text-lg mb-4 text-center focus:border-blue-600 outline-none font-bold text-gray-800" placeholder="Enter Device Name" value={name} onChange={e => setName(e.target.value)} autoFocus />
                <button disabled={!name} onClick={() => onSave(name)} className="w-full bg-blue-600 text-white py-4 rounded-xl font-bold text-lg disabled:opacity-50 hover:bg-blue-700 transition-colors shadow-lg shadow-blue-200">Save Device Name</button>
            </div>
        </div>
    );
};

const BarcodeScanner = ({ onScan, onClose }) => {
    const scannerRef = useRef(null);
    const [isMounted, setIsMounted] = useState(true);
    const [zoom, setZoom] = useState(1);
    const [capabilities, setCapabilities] = useState(null);

    useEffect(() => {
        setIsMounted(true);
        const initTimer = setTimeout(() => {
            if (!isMounted) return;
            const html5QrCode = new Html5Qrcode("reader");
            scannerRef.current = html5QrCode;
            const config = { fps: 15, qrbox: { width: 280, height: 180 }, aspectRatio: 1.0, formatsToSupport: [ Html5QrcodeSupportedFormats.CODE_128 ] };
            html5QrCode.start({ facingMode: "environment" }, config, (decodedText) => { if (isMounted) onScan(decodedText); }, () => {} ).then(() => {
                const track = html5QrCode.getRunningTrackCameraCapabilities();
                if(track && track.zoomFeature()) { setCapabilities(track); }
            }).catch(err => console.log("Camera Error", err));
        }, 300);
        return () => {
            setIsMounted(false);
            clearTimeout(initTimer);
            if (scannerRef.current) { try { scannerRef.current.stop().then(() => scannerRef.current.clear()).catch(e => console.log(e)); } catch (e) { console.log(e); } }
        };
    }, [onScan]);

    const handleZoomChange = (e) => {
        const newZoom = Number(e.target.value);
        setZoom(newZoom);
        if(scannerRef.current && capabilities) { scannerRef.current.applyVideoConstraints({ focusMode: "continuous", advanced: [{ zoom: newZoom }] }); }
    };

    return (
        <div className="fixed inset-0 bg-black/90 z-[100] flex flex-col items-center justify-center p-4">
            <div className="w-full max-w-sm bg-white rounded-xl overflow-hidden p-4">
                 <h3 className="text-center font-bold mb-2">Scan Roll Barcode</h3>
                 <div id="reader" className="w-full bg-black min-h-[300px]"></div>
                 {capabilities && (<div className="mt-4 px-2"><div className="flex justify-between text-xs font-bold text-gray-500 mb-1"><span>1x</span> <span className="flex items-center gap-1"><ZoomIn size={12}/> Zoom</span> <span>Max</span></div><input type="range" min={capabilities.zoomFeature().min()} max={capabilities.zoomFeature().max()} step="0.1" value={zoom} onChange={handleZoomChange} className="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer" /></div>)}
                 <button onClick={onClose} className="w-full mt-4 bg-red-100 text-red-600 py-3 rounded-lg font-bold">Close Scanner</button>
            </div>
        </div>
    );
};

// --- IMAGE-PERFECT LABEL PRINT ---
const LabelPrint = ({ data, onClose }) => {
  // --- Load Settings from Memory ---
  const savedDesign = JSON.parse(localStorage.getItem('ksf_label_design_v3') || '{}');
  const savedLabels = JSON.parse(localStorage.getItem('ksf_label_labels_v3') || '{}');

  // State initialization with fallbacks
  const [showLogo, setShowLogo] = useState(savedDesign.showLogo ?? true);
  const [labelSize, setLabelSize] = useState(savedDesign.labelSize || '4in-3in');
  const [baseFontSize, setBaseFontSize] = useState(savedDesign.baseFontSize || 14); 
  const [logoSize, setLogoSize] = useState(savedDesign.logoSize || 50);
  const [barcodeScale, setBarcodeScale] = useState(savedDesign.barcodeScale || 50);

  // Content State - Pre-populated with defaults from the image logic
  const [content, setContent] = useState({
      qualityLabel: savedLabels.qualityLabel || 'Quality:', qualityVal: data.quality,
      gsmLabel: savedLabels.gsmLabel || 'GSM:', gsmVal: data.gsm,
      colorLabel: savedLabels.colorLabel || 'Color:', colorVal: data.color,
      widthLabel: savedLabels.widthLabel || 'Width:', widthVal: `${data.width_inches}"`,
      lengthLabel: savedLabels.lengthLabel || 'Length:', lengthVal: `${data.length_meters}m`,
      netLabel: savedLabels.netLabel || 'Net Wt:', netVal: `${data.net_weight}kg`,
      grossLabel: savedLabels.grossLabel || 'Gross Wt:', grossVal: `${data.gross_weight}kg`
  });

  const canvasRef = useRef(null);

  // Auto-Save
  useEffect(() => {
      const designSettings = { showLogo, labelSize, baseFontSize, logoSize, barcodeScale };
      const labelSettings = { ...content };
      localStorage.setItem('ksf_label_design_v3', JSON.stringify(designSettings));
      localStorage.setItem('ksf_label_labels_v3', JSON.stringify(labelSettings));
  }, [showLogo, labelSize, baseFontSize, logoSize, barcodeScale, content]);

  // Barcode Render
  useEffect(() => {
      if (data && canvasRef.current) {
          try { 
              JsBarcode(canvasRef.current, data.product_id, { 
                  format: "CODE128", 
                  width: 2.5, 
                  height: barcodeScale, 
                  displayValue: false, 
                  margin: 0,
              }); 
          } catch (e) { console.error(e); }
      }
  }, [data, barcodeScale]);

  const handlePrint = () => window.print();
  const handleChange = (field, val) => setContent(prev => ({...prev, [field]: val}));

  if (!data) return null;

  const [width, height] = labelSize.split('-');

  // --- STYLES ---
  // Replicating the image's Monospaced look
  const fontStyle = { fontFamily: "'Courier New', Courier, monospace" };
  
  const labelInputStyle = {
      ...fontStyle,
      background: 'transparent', border: 'none', width: 'auto', outline: 'none', padding: 0, margin: 0,
      color: '#000', fontSize: `${baseFontSize}px`, fontWeight: '900', textAlign: 'left',
      minWidth: '60px' // Ensure label has some width
  };
  
  const valueInputStyle = {
      ...fontStyle,
      background: 'transparent', border: 'none', width: '100%', outline: 'none', padding: 0, margin: 0,
      color: '#000', fontSize: `${baseFontSize}px`, fontWeight: '500', textAlign: 'left'
  };

  const printStyle = {
      width: width, height: height, backgroundColor: 'white', overflow: 'hidden',
      display: 'flex', flexDirection: 'column', justifyContent: 'flex-start',
      padding: '10px', border: '6px solid black', boxSizing: 'border-box', ...fontStyle
  };

  const rowStyle = { display: 'flex', justifyContent: 'space-between', marginBottom: '4px' };
  const colStyle = { display: 'flex', gap: '4px', flex: 1 };

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-[100] p-4 overflow-y-auto">
      <style>{`@media print { body * { visibility: hidden; } #print-wrapper, #print-wrapper * { visibility: visible; } #print-wrapper { position: absolute; top: 0; left: 0; margin: 0; border: none !important; } #print-controls { display: none !important; } }`}</style>

      <div className="bg-white p-4 rounded-xl max-w-lg w-full flex flex-col items-center animate-in fade-in zoom-in-95 my-auto">
        
        {/* DESIGN TOOLBAR */}
        <div id="print-controls" className="w-full mb-4 space-y-3 bg-slate-50 p-3 rounded-lg border border-slate-200">
             <div className="flex justify-between items-center">
                <span className="text-xs font-bold text-slate-500 uppercase"><Settings size={14} className="inline mr-1"/>Settings</span>
                <select className="border rounded p-1 text-xs font-bold" value={labelSize} onChange={(e) => setLabelSize(e.target.value)}>
                    <option value="4in-3in">4" x 3"</option>
                    <option value="4in-4in">4" x 4"</option>
                    <option value="4in-2in">4" x 2"</option>
                </select>
            </div>
             <div className="flex items-center justify-between border-t border-slate-200 pt-2">
                <span className="text-xs font-bold text-slate-500">Font Size</span>
                 <div className="flex gap-1 bg-white p-1 rounded border">
                    <button onClick={() => setBaseFontSize(f => Math.max(10, f-1))} className="p-1 hover:bg-slate-100 rounded"><Minus size={14}/></button>
                    <span className="text-xs font-bold w-6 text-center pt-0.5">{baseFontSize}</span>
                    <button onClick={() => setBaseFontSize(f => Math.min(30, f+1))} className="p-1 hover:bg-slate-100 rounded"><PlusIcon size={14}/></button>
                </div>
            </div>
            <div className="grid grid-cols-2 gap-4 pt-1 border-t border-slate-200">
                <div><label className="text-[10px] font-bold text-slate-400 block mb-1">Logo Size</label><input type="range" min="30" max="100" value={logoSize} onChange={e => setLogoSize(Number(e.target.value))} className="w-full h-1 bg-slate-300 rounded-lg appearance-none cursor-pointer"/></div>
                <div><label className="text-[10px] font-bold text-slate-400 block mb-1">Barcode</label><input type="range" min="30" max="120" value={barcodeScale} onChange={e => setBarcodeScale(Number(e.target.value))} className="w-full h-1 bg-slate-300 rounded-lg appearance-none cursor-pointer"/></div>
            </div>
             <div className="flex items-center justify-between border-t border-slate-200 pt-2">
                <span className="text-xs font-bold text-slate-500">Show Logo</span>
                <button onClick={() => setShowLogo(!showLogo)} className={`w-8 h-4 rounded-full transition-colors ${showLogo ? 'bg-green-500' : 'bg-slate-300'}`}></button>
            </div>
        </div>

        {/* PRINT PREVIEW AREA - EXACT IMAGE REPLICA */}
        <div id="print-wrapper" className="flex items-center justify-center bg-gray-200 p-6 rounded-lg border border-dashed border-gray-400 overflow-auto max-h-[70vh] w-full">
            <div id="print-area" style={printStyle}>
                
                {/* Header: Just Logo (Centered) - Text removed as requested */}
                <div className="w-full flex justify-center pb-2">
                    {showLogo && <img src="/logo.png" style={{ height: `${logoSize}px`, objectFit: 'contain' }} alt="Logo" />}
                    {!showLogo && <div style={{height: '10px'}}></div>} 
                </div>

                {/* The Thick Divider Line */}
                <div style={{ width: '100%', borderTop: '3px solid black', marginBottom: '8px' }}></div>

                {/* Line 1: Quality | GSM */}
                <div style={rowStyle}>
                    <div style={colStyle}>
                        <input style={labelInputStyle} value={content.qualityLabel} onChange={e => handleChange('qualityLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.qualityVal} onChange={e => handleChange('qualityVal', e.target.value)} />
                    </div>
                    <div style={{...colStyle, justifyContent: 'flex-start', flex: 0.6}}>
                        <input style={{...labelInputStyle, minWidth: '40px'}} value={content.gsmLabel} onChange={e => handleChange('gsmLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.gsmVal} onChange={e => handleChange('gsmVal', e.target.value)} />
                    </div>
                </div>

                {/* Line 2: Color | Width */}
                <div style={rowStyle}>
                    <div style={colStyle}>
                        <input style={labelInputStyle} value={content.colorLabel} onChange={e => handleChange('colorLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.colorVal} onChange={e => handleChange('colorVal', e.target.value)} />
                    </div>
                    <div style={{...colStyle, justifyContent: 'flex-start', flex: 0.6}}>
                        <input style={{...labelInputStyle, minWidth: '60px'}} value={content.widthLabel} onChange={e => handleChange('widthLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.widthVal} onChange={e => handleChange('widthVal', e.target.value)} />
                    </div>
                </div>

                {/* Line 3: Length | Net Wt */}
                <div style={rowStyle}>
                    <div style={colStyle}>
                        <input style={labelInputStyle} value={content.lengthLabel} onChange={e => handleChange('lengthLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.lengthVal} onChange={e => handleChange('lengthVal', e.target.value)} />
                    </div>
                    <div style={{...colStyle, justifyContent: 'flex-start', flex: 0.6}}>
                        <input style={{...labelInputStyle, minWidth: '70px'}} value={content.netLabel} onChange={e => handleChange('netLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.netVal} onChange={e => handleChange('netVal', e.target.value)} />
                    </div>
                </div>

                {/* Line 4: Gross Wt (Combined) */}
                <div style={{ ...rowStyle, marginTop: '4px', marginBottom: '8px' }}>
                    <div style={colStyle}>
                        <input style={{...labelInputStyle, minWidth: '85px'}} value={content.grossLabel} onChange={e => handleChange('grossLabel', e.target.value)} />
                        <input style={valueInputStyle} value={content.grossVal} onChange={e => handleChange('grossVal', e.target.value)} />
                    </div>
                </div>

                {/* Footer: Barcode & ID */}
                <div className="w-full flex flex-col items-center justify-end mt-auto pt-2">
                    <canvas ref={canvasRef} style={{ maxWidth: '100%', height: 'auto' }}></canvas>
                    <div style={{ fontWeight: 'bold', fontSize: `${baseFontSize * 1.3}px`, marginTop: '2px', ...fontStyle }}>
                        {data.product_id}
                    </div>
                </div>
            </div>
        </div>

        <div id="print-controls" className="flex gap-3 w-full mt-4">
          <button onClick={handlePrint} className="flex-1 bg-blue-600 text-white py-3 rounded-xl flex items-center justify-center gap-2 font-bold shadow-lg shadow-blue-200 hover:bg-blue-700 transition-colors"><Printer size={20} /> Print Label</button>
          <button onClick={onClose} className="flex-1 bg-gray-100 text-gray-600 py-3 rounded-xl font-bold hover:bg-gray-200 transition-colors">Close</button>
        </div>

      </div>
    </div>
  );
};

const NewProductView = ({ formData, setFormData, onSubmit }) => {
  return (
    <div className="max-w-xl mx-auto bg-white p-5 rounded-xl shadow-sm border border-gray-100 mt-2">
      <h2 className="text-lg font-bold mb-4 flex items-center gap-2 text-gray-800 border-b pb-2"><Plus className="text-blue-600" size={20}/> New Roll Entry</h2>
      <form onSubmit={onSubmit} className="grid grid-cols-2 gap-3">
        <div className="col-span-2"><label className="text-xs font-bold text-gray-500 uppercase ml-1">Customer</label><input placeholder="Internal Name" required className="w-full bg-gray-50 border-gray-200 border p-2.5 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" value={formData.customer_name} onChange={e => setFormData({...formData, customer_name: e.target.value})} /></div>
        <div><label className="text-xs font-bold text-gray-500 uppercase ml-1">Quality</label><select required className="w-full bg-gray-50 border-gray-200 border p-2.5 rounded-lg" value={formData.quality} onChange={e => setFormData({...formData, quality: e.target.value})}><option value="">Select...</option>{QUALITIES.map(q => <option key={q} value={q}>{q}</option>)}</select></div>
        <div><label className="text-xs font-bold text-gray-500 uppercase ml-1">Color</label><select required className="w-full bg-gray-50 border-gray-200 border p-2.5 rounded-lg" value={formData.color} onChange={e => setFormData({...formData, color: e.target.value})}><option value="">Select...</option>{COLORS.map(c => <option key={c} value={c}>{c}</option>)}</select></div>
        <div className="col-span-2 grid grid-cols-3 gap-3"><div><label className="text-xs font-bold text-gray-500 uppercase ml-1">GSM</label><input type="number" className="w-full bg-gray-50 border-gray-200 border p-2.5 rounded-lg" value={formData.gsm} onChange={e => setFormData({...formData, gsm: e.target.value})} /></div><div><label className="text-xs font-bold text-gray-500 uppercase ml-1">Width (In)</label><input type="number" className="w-full bg-gray-50 border-gray-200 border p-2.5 rounded-lg" value={formData.width_inches} onChange={e => setFormData({...formData, width_inches: e.target.value})} /></div><div><label className="text-xs font-bold text-gray-500 uppercase ml-1">Length (m)</label><input type="number" className="w-full bg-gray-50 border-gray-200 border p-2.5 rounded-lg" value={formData.length_meters} onChange={e => setFormData({...formData, length_meters: e.target.value})} /></div></div>
        <div className="col-span-2 grid grid-cols-2 gap-3 bg-blue-50 p-3 rounded-lg border border-blue-100"><div><label className="text-xs font-bold text-blue-800 uppercase ml-1">Net Kg</label><input type="number" className="w-full bg-white border-blue-200 border p-2.5 rounded-lg font-bold text-blue-900" value={formData.net_weight} onChange={e => setFormData({...formData, net_weight: e.target.value})} /></div><div><label className="text-xs font-bold text-blue-800 uppercase ml-1">Gross Kg</label><input type="number" className="w-full bg-white border-blue-200 border p-2.5 rounded-lg" value={formData.gross_weight} onChange={e => setFormData({...formData, gross_weight: e.target.value})} /></div></div>
        <button type="submit" className="col-span-2 mt-2 bg-blue-600 hover:bg-blue-700 active:scale-95 transition-all text-white py-3.5 rounded-xl font-bold text-lg shadow-lg shadow-blue-200">Save & Print Label</button>
      </form>
    </div>
  );
};

const EditModal = ({ roll, isGuest, onClose, onSave, onDelete }) => {
    const [editData, setEditData] = useState({ ...roll });
    const handleDelete = () => { if(window.confirm("PERMANENTLY DELETE this roll from database?")) { onDelete(roll.id); onClose(); } };
    const handleReturnToStock = () => { if(window.confirm("Undo Dispatch? This will move the roll back to Stock.")) { onSave({ ...editData, status: 'in_stock', dispatched_at: null }); } };

    return (
        <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-[100] p-4">
            <div className="bg-white p-5 rounded-xl max-w-lg w-full animate-in fade-in zoom-in-95 duration-200">
                <div className="flex justify-between items-center mb-4 border-b pb-2"><h2 className="text-lg font-bold flex items-center gap-2"><Package size={18} className="text-blue-600"/> Roll Details</h2><button onClick={onClose}><X size={24} className="text-gray-400 hover:text-red-500"/></button></div>
                {isGuest && <div className="bg-orange-50 text-orange-700 text-sm font-bold p-2 text-center rounded mb-4">Read Only Mode</div>}
                {roll.status === 'dispatched' && <div className="bg-green-50 text-green-700 text-sm font-bold p-2 text-center rounded mb-4">Status: DISPATCHED</div>}
                <div className="bg-blue-50 p-3 rounded-lg mb-4 text-center"><div className="text-xs text-blue-600 uppercase font-bold">Product ID</div><div className="text-xl font-mono font-black text-blue-900">{roll.product_id}</div></div>
                <div className="grid grid-cols-2 gap-3 mb-6"><div className="col-span-2"><label className="text-xs font-bold text-gray-500 uppercase">Customer</label><input disabled={isGuest} className="w-full border p-2.5 rounded-lg bg-gray-50" value={editData.customer_name || ''} onChange={e => setEditData({...editData, customer_name: e.target.value})} /></div><div><label className="text-xs font-bold text-gray-500 uppercase">Quality</label><input disabled={isGuest} className="w-full border p-2.5 rounded-lg" value={editData.quality} onChange={e => setEditData({...editData, quality: e.target.value})} /></div><div><label className="text-xs font-bold text-gray-500 uppercase">Color</label><input disabled={isGuest} className="w-full border p-2.5 rounded-lg" value={editData.color} onChange={e => setEditData({...editData, color: e.target.value})} /></div><div><label className="text-xs font-bold text-gray-500 uppercase">Net Kg</label><input disabled={isGuest} type="number" className="w-full border p-2.5 rounded-lg font-bold" value={editData.net_weight} onChange={e => setEditData({...editData, net_weight: e.target.value})} /></div><div><label className="text-xs font-bold text-gray-500 uppercase">Gross Kg</label><input disabled={isGuest} type="number" className="w-full border p-2.5 rounded-lg" value={editData.gross_weight} onChange={e => setEditData({...editData, gross_weight: e.target.value})} /></div></div>
                {!isGuest && (<div className="flex flex-col gap-3">{roll.status === 'dispatched' && (<button onClick={handleReturnToStock} className="w-full bg-orange-100 text-orange-700 border border-orange-200 py-3 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-orange-200 transition-colors"><RotateCcw size={18}/> Return to Stock</button>)}<button onClick={() => onSave(editData)} className="w-full bg-blue-600 text-white py-3.5 rounded-xl font-bold shadow-lg shadow-blue-200">Save Changes</button><button onClick={handleDelete} className="w-full bg-white border border-red-200 text-red-600 py-3 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-red-50"><Trash2 size={18}/> Delete Roll</button></div>)}
            </div>
        </div>
    );
};

const StockView = ({ rolls, onPrint, onExport, onSelectRoll }) => {
  const [search, setSearch] = useState('');
  const [filters, setFilters] = useState({ color: 'All', quality: 'All', gsm: 'All' });
  const uniqueColors = ['All', ...new Set(rolls.map(r => r.color).filter(Boolean))];
  const uniqueQualities = ['All', ...new Set(rolls.map(r => r.quality).filter(Boolean))];
  const uniqueGSM = ['All', ...new Set(rolls.map(r => r.gsm).filter(Boolean))];
  const filtered = rolls.filter(r => {
      const term = search.toLowerCase();
      const matchSearch = r.status === 'in_stock' && ((r.product_id || '').toLowerCase().includes(term) || (r.customer_name || '').toLowerCase().includes(term) || (r.quality || '').toLowerCase().includes(term) || (r.color || '').toLowerCase().includes(term) || String(r.gsm || '').toLowerCase().includes(term) || String(r.width_inches || '').toLowerCase().includes(term) || String(r.net_weight || '').toLowerCase().includes(term));
      const matchColor = filters.color === 'All' || r.color === filters.color;
      const matchQuality = filters.quality === 'All' || r.quality === filters.quality;
      const matchGSM = filters.gsm === 'All' || r.gsm == filters.gsm;
      return matchSearch && matchColor && matchQuality && matchGSM;
  });

  return (
      <div className="space-y-4 h-full flex flex-col">
          <div className="sticky top-0 bg-slate-50 z-10 pb-2 space-y-2"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-gray-400" size={18}/><input className="w-full pl-10 p-2.5 bg-white border-gray-200 border rounded-xl shadow-sm focus:ring-2 focus:ring-blue-500 outline-none" placeholder="Search (Cust, ID, Wt...)" value={search} onChange={e => setSearch(e.target.value)} /></div><button onClick={onExport} className="bg-white border border-green-200 text-green-700 p-2.5 rounded-xl shadow-sm"><Download size={20} /></button></div><div className="flex gap-2 overflow-x-auto no-scrollbar"><select className="bg-white border p-2 rounded-lg text-xs font-bold text-gray-600 min-w-[100px]" value={filters.color} onChange={e => setFilters({...filters, color: e.target.value})}>{uniqueColors.map(c => <option key={c} value={c}>Color: {c}</option>)}</select><select className="bg-white border p-2 rounded-lg text-xs font-bold text-gray-600 min-w-[100px]" value={filters.quality} onChange={e => setFilters({...filters, quality: e.target.value})}>{uniqueQualities.map(q => <option key={q} value={q}>Qual: {q}</option>)}</select><select className="bg-white border p-2 rounded-lg text-xs font-bold text-gray-600 min-w-[80px]" value={filters.gsm} onChange={e => setFilters({...filters, gsm: e.target.value})}>{uniqueGSM.map(g => <option key={g} value={g}>GSM: {g}</option>)}</select></div></div>
          <div className="flex-1 overflow-y-auto pb-20">{filtered.map(r => (<div key={r.id} onClick={() => onSelectRoll(r)} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 mb-3 flex justify-between items-center active:bg-blue-50 transition-colors cursor-pointer"><div><div className="flex flex-wrap items-center gap-2 mb-1"><span className="font-mono font-bold text-xs text-blue-600 bg-blue-50 px-2 py-0.5 rounded">{r.product_id}</span><span className="text-xs font-extrabold text-gray-800 uppercase tracking-wide">{r.customer_name}</span></div><div className="text-gray-900 font-medium text-sm">{r.quality} • {r.color} • {r.width_inches}" • {r.gsm} GSM</div><div className="text-sm text-gray-500 mt-1">Wt: <strong>{r.net_weight}kg</strong> • Len: {r.length_meters}m</div></div><button onClick={(e) => { e.stopPropagation(); onPrint(r); }} className="p-3 text-gray-400 hover:text-blue-600 bg-gray-50 rounded-lg"><Printer size={20}/></button></div>))}{filtered.length === 0 && <div className="text-center text-gray-400 py-10">No Stock Found</div>}</div>
      </div>
  );
};

const HistoryView = ({ rolls, onSelectRoll, onExport }) => {
    const history = useMemo(() => rolls.filter(r => r.status === 'dispatched').sort((a, b) => new Date(b.dispatched_at) - new Date(a.dispatched_at)), [rolls]);
    const totalDispatchedWeight = history.reduce((acc, curr) => acc + parseFloat(curr.net_weight || 0), 0);
    return (
        <div className="space-y-4 h-full flex flex-col"><div className="bg-slate-800 text-white p-5 rounded-xl shadow-md relative"><button onClick={() => onExport(history)} className="absolute top-4 right-4 bg-white/10 p-2 rounded-lg text-white hover:bg-white/20"><Download size={18}/></button><div className="flex items-center gap-2 mb-2 text-slate-300 text-sm uppercase font-bold tracking-wider"><Clock size={16}/> Dispatch Log</div><div className="flex justify-between items-end"><div><div className="text-3xl font-black">{history.length}</div><div className="text-xs text-slate-400">Rolls Sent</div></div><div className="text-right"><div className="text-3xl font-black text-green-400">{totalDispatchedWeight.toLocaleString()}</div><div className="text-xs text-slate-400">Total Kg</div></div></div></div><div className="flex-1 overflow-y-auto pb-20">{history.map(r => (<div key={r.id} onClick={() => onSelectRoll(r)} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 mb-3 relative cursor-pointer hover:bg-gray-50"><div className="absolute top-4 right-4 text-xs font-bold text-gray-400 bg-gray-100 px-2 py-1 rounded">{new Date(r.dispatched_at).toLocaleDateString()}</div><div className="mb-2"><span className="font-mono font-bold text-xs text-slate-500 bg-slate-100 px-2 py-0.5 rounded">{r.product_id}</span></div><div className="grid grid-cols-2 gap-y-1 text-sm text-gray-600"><div>To: <span className="font-bold text-gray-900">{r.customer_name || 'Unknown'}</span></div><div>Wt: <span className="font-bold text-gray-900">{r.net_weight} kg</span></div></div></div>))}</div></div>
    );
};

const AnalyticsDashboard = ({ rolls }) => {
    const last7Days = [...Array(7)].map((_, i) => { const d = new Date(); d.setDate(d.getDate() - i); return d.toISOString().split('T')[0]; }).reverse();
    const productionData = last7Days.map(date => { const count = rolls.filter(r => r.created_at.startsWith(date)).length; return { name: date.slice(5), rolls: count }; });
    const stockRolls = rolls.filter(r => r.status === 'in_stock');
    const colorMap = stockRolls.reduce((acc, r) => { acc[r.color] = (acc[r.color] || 0) + 1; return acc; }, {});
    const pieData = Object.keys(colorMap).map(k => ({ name: k, value: colorMap[k] }));
    const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884d8', '#ff7300'];
    return (
        <div className="space-y-4"><div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100"><h3 className="font-bold text-gray-700 mb-4 text-sm">Production (Last 7 Days)</h3><div className="h-48 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={productionData}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="name" fontSize={10} /><YAxis fontSize={10} /><RechartsTooltip /><Bar dataKey="rolls" fill="#3b82f6" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></div><div className="bg-white p-4 rounded-xl shadow-sm border border-gray-100"><h3 className="font-bold text-gray-700 mb-4 text-sm">Stock by Color</h3><div className="h-48 w-full"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} cx="50%" cy="50%" outerRadius={60} fill="#8884d8" dataKey="value" label={({name})=>name}>{pieData.map((entry, index) => <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />)}</Pie><RechartsTooltip /></PieChart></ResponsiveContainer></div></div></div>
    );
};

const Dashboard = ({ rolls, materials }) => {
    const totalRolls = rolls.filter(r => r.status === 'in_stock').length;
    const totalWeight = rolls.filter(r => r.status === 'in_stock').reduce((acc, curr) => acc + parseFloat(curr.net_weight || 0), 0);
    const recentActivity = rolls.slice(0, 5);

    return (
        <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4"><div className="bg-gradient-to-br from-blue-600 to-blue-700 text-white p-5 rounded-2xl shadow-lg shadow-blue-200"><div className="text-blue-100 text-xs font-bold uppercase tracking-wide mb-1">Total Stock</div><div className="text-3xl font-black">{totalRolls}</div><div className="text-blue-200 text-xs mt-1">Rolls Available</div></div><div className="bg-gradient-to-br from-purple-600 to-purple-700 text-white p-5 rounded-2xl shadow-lg shadow-purple-200"><div className="text-purple-100 text-xs font-bold uppercase tracking-wide mb-1">Total Weight</div><div className="text-3xl font-black">{totalWeight.toLocaleString()}</div><div className="text-purple-200 text-xs mt-1">Kilograms</div></div></div>
            <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100"><div className="text-gray-900 font-bold mb-3 flex items-center gap-2"><Activity size={18} className="text-blue-500"/> Recent Activity (Live)</div><div className="space-y-3">{recentActivity.map(r => (<div key={r.id} className="flex justify-between items-center text-sm border-b pb-2 last:border-0"><div><div className="flex items-center gap-2"><span className="font-bold text-gray-700">{r.product_id}</span> <span className={`text-[10px] font-bold px-1.5 py-0.5 rounded uppercase ${r.status === 'dispatched' ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'}`}>{r.status === 'in_stock' ? 'Added/Edited' : 'Dispatched'}</span></div><div className="text-[10px] text-gray-400 mt-0.5 flex items-center gap-1"><Smartphone size={10}/> {r.device_name || 'Unknown Device'}</div></div><div className="text-xs text-gray-400 font-mono">{new Date(r.updated_at).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}</div></div>))}</div></div>
            <AnalyticsDashboard rolls={rolls} />
            <div className="bg-white p-5 rounded-2xl shadow-sm border border-gray-100"><div className="text-gray-900 font-bold mb-3 flex items-center gap-2"><AlertCircle size={18} className="text-orange-500"/> Low Material Alerts</div><div className="space-y-2">{materials.filter(m => m.stock_quantity < 100).length > 0 ? (materials.filter(m => m.stock_quantity < 100).map(m => (<div key={m.id} className="flex justify-between items-center bg-red-50 p-3 rounded-lg border border-red-100"><span className="text-red-900 font-medium text-sm">{m.name}</span><span className="text-red-700 font-bold text-sm">{m.stock_quantity} kg</span></div>))) : <div className="text-green-600 text-sm bg-green-50 p-3 rounded-lg border border-green-100 text-center">All materials sufficient</div>}</div></div>
        </div>
    );
};

const DispatchView = ({ rolls, isGuest, deviceName, onDispatch, onUpdateRoll }) => {
    const [scanId, setScanId] = useState('');
    const [foundRoll, setFoundRoll] = useState(null);
    const [editedRoll, setEditedRoll] = useState(null);
    const [showScanner, setShowScanner] = useState(false);
    const [sessionList, setSessionList] = useState([]);
    const [challanDetails, setChallanDetails] = useState({ vehicle: '', buyer: '' });

    const handleSearch = useCallback((idOverride) => {
        const query = idOverride || scanId;
        const roll = rolls.find(r => r.product_id === query && r.status === 'in_stock');
        if (roll) { setFoundRoll(roll); setEditedRoll({ ...roll }); setScanId(query); setShowScanner(false); } 
        else { alert('Roll not found or already dispatched.'); }
    }, [rolls, scanId]);

    const handleConfirmDispatch = async () => {
        if (editedRoll.net_weight !== foundRoll.net_weight || editedRoll.customer_name !== foundRoll.customer_name) { await onUpdateRoll(editedRoll); }
        onDispatch(editedRoll.id);
        setSessionList(prev => [...prev, editedRoll]);
        setFoundRoll(null);
        setEditedRoll(null);
        setScanId('');
    };

    const handlePrintChallan = () => {
        if(!challanDetails.buyer || !challanDetails.vehicle) return alert("Enter Buyer Name and Vehicle No first!");
        generateChallan(sessionList, { ...challanDetails, device: deviceName });
        if(window.confirm("Clear this Challan list?")) { setSessionList([]); setChallanDetails({ vehicle: '', buyer: '' }); }
    };

    return (
        <div className="max-w-xl mx-auto space-y-4">
            {showScanner && <BarcodeScanner onScan={(text) => { if(text) handleSearch(text); else setShowScanner(false); }} onClose={() => setShowScanner(false)} />}
            <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100 text-center"><div className="mb-4"><h2 className="text-lg font-bold mb-2 text-gray-800">Scan Barcode</h2><input className="w-full bg-gray-50 border-2 border-gray-200 p-4 text-center text-xl font-mono tracking-widest rounded-xl focus:border-blue-500 focus:bg-white outline-none transition-all" placeholder="Type or Scan" value={scanId} onChange={(e) => setScanId(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && handleSearch()}/></div><div className="grid grid-cols-2 gap-3"><button onClick={() => setShowScanner(true)} className="bg-blue-600 hover:bg-blue-700 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2"><Camera size={20}/> Camera</button><button onClick={() => handleSearch()} className="bg-gray-900 text-white py-3 rounded-xl font-bold">Search</button></div></div>
            {foundRoll && editedRoll && (<div className="bg-green-50 border border-green-200 p-5 rounded-xl animate-in fade-in slide-in-from-bottom-4"><h3 className="font-bold text-green-900 mb-4 flex items-center gap-2"><Package size={20}/> Ready to Dispatch</h3><div className="bg-white/70 p-4 rounded-lg grid grid-cols-2 gap-3 text-sm mb-4 border border-green-100"><div className="col-span-2 text-center border-b pb-2 mb-1"><span className="text-gray-500 text-xs">ID:</span> <span className="font-mono font-bold text-lg">{foundRoll.product_id}</span></div><div><label className="text-xs text-gray-500 font-bold uppercase">Customer</label><input className="w-full border p-2 rounded bg-white" value={editedRoll.customer_name || ''} onChange={e => setEditedRoll({...editedRoll, customer_name: e.target.value})} /></div><div><label className="text-xs text-gray-500 font-bold uppercase">Weight (Kg)</label><input type="number" className="w-full border p-2 rounded bg-white font-bold text-green-800" value={editedRoll.net_weight} onChange={e => setEditedRoll({...editedRoll, net_weight: e.target.value})} /></div><div><label className="text-xs text-gray-500 font-bold uppercase">Quality</label><input className="w-full border p-2 rounded bg-white" value={editedRoll.quality} onChange={e => setEditedRoll({...editedRoll, quality: e.target.value})} /></div><div><label className="text-xs text-gray-500 font-bold uppercase">Color</label><input className="w-full border p-2 rounded bg-white" value={editedRoll.color} onChange={e => setEditedRoll({...editedRoll, color: e.target.value})} /></div></div>{isGuest ? (<div className="bg-orange-100 text-orange-700 p-3 rounded-lg font-bold text-center">Login to Dispatch</div>) : (<button onClick={handleConfirmDispatch} className="w-full bg-green-600 hover:bg-green-700 text-white py-3.5 rounded-xl font-bold text-lg shadow-lg shadow-green-200 flex items-center justify-center gap-2"><CheckCircle size={20}/> CONFIRM & DISPATCH</button>)}</div>)}
            {!isGuest && sessionList.length > 0 && (<div className="bg-blue-50 border border-blue-200 p-5 rounded-xl mt-6"><div className="flex justify-between items-center mb-4"><h3 className="font-bold text-blue-900 flex items-center gap-2"><FileText size={20}/> Gate Pass Generator</h3><span className="bg-blue-200 text-blue-800 text-xs font-bold px-2 py-1 rounded-full">{sessionList.length} Items</span></div><input className="w-full border p-2 mb-2 rounded" placeholder="Buyer Name" value={challanDetails.buyer} onChange={e => setChallanDetails({...challanDetails, buyer: e.target.value})} /><input className="w-full border p-2 mb-4 rounded" placeholder="Vehicle No (e.g. UP 27 ...)" value={challanDetails.vehicle} onChange={e => setChallanDetails({...challanDetails, vehicle: e.target.value})} /><button onClick={handlePrintChallan} className="w-full bg-blue-600 text-white py-3 rounded-xl font-bold flex items-center justify-center gap-2 shadow-lg"><Printer size={18}/> Download Gate Pass PDF</button></div>)}
        </div>
    );
};

const MaterialsView = ({ materials, isGuest, onUpdate, onAdd }) => { const handleUpdate = (id, type) => { const qty = prompt(`Enter quantity to ${type} (Kg):`); if (qty && !isNaN(qty)) onUpdate(id, qty, type === 'add'); }; const handleAdd = () => { const name = prompt("Enter Material Name:"); if(name) onAdd(name); }; return (<div className="pb-20">{!isGuest && <button onClick={handleAdd} className="w-full bg-white border-2 border-dashed border-gray-300 text-gray-500 py-3 rounded-xl font-bold mb-4 hover:border-blue-400 hover:text-blue-500 transition-colors">+ Add New Material</button>}<div className="grid grid-cols-1 gap-3">{materials.map(m => (<div key={m.id} className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex items-center justify-between"><div><h3 className="font-bold text-gray-700 text-sm">{m.name}</h3><div className="text-2xl font-black text-gray-900">{m.stock_quantity} <span className="text-xs font-medium text-gray-400">{m.unit}</span></div></div>{!isGuest && <div className="flex gap-2"><button onClick={() => handleUpdate(m.id, 'issue')} className="w-10 h-10 flex items-center justify-center bg-red-50 text-red-600 rounded-lg font-bold border border-red-100">-</button><button onClick={() => handleUpdate(m.id, 'add')} className="w-10 h-10 flex items-center justify-center bg-green-50 text-green-600 rounded-lg font-bold border border-green-100">+</button></div>}</div>))}</div></div>); };

// --- MAIN APP ---
export default function App() {
  const [user, setUser] = useState(null);
  const [isGuest, setIsGuest] = useState(false);
  const [deviceName, setDeviceName] = useState(localStorage.getItem('ksf_device_name') || '');
  const [activeTab, setActiveTab] = useState('dashboard');
  const [loading, setLoading] = useState(false);
  const [rolls, setRolls] = useState([]);
  const [materials, setMaterials] = useState([]);
  const [printData, setPrintData] = useState(null);
  const [editRoll, setEditRoll] = useState(null);
  const [formData, setFormData] = useState({ customer_name: '', quality: '', gsm: '', color: '', width_inches: '', length_meters: '', net_weight: '', gross_weight: '' });

  useEffect(() => {
    const checkSession = async () => { const { data: { session } } = await supabase.auth.getSession(); if (session) { setUser(session.user); setIsGuest(false); fetchData(); } };
    checkSession();
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => { setUser(session?.user ?? null); if (session) { setIsGuest(false); fetchData(); } });
    return () => subscription.unsubscribe();
  }, []);

  const fetchData = async () => { setLoading(true); const r = await DataService.getStock(); const m = await DataService.getRawMaterials(); setRolls(r || []); setMaterials(m || []); setLoading(false); };
  const handleLogin = async () => { await supabase.auth.signInWithOAuth({ provider: 'google', options: { redirectTo: window.location.origin } }); };
  const handleGuestEntry = () => { setIsGuest(true); fetchData(); };
  const handleLogout = async () => { await supabase.auth.signOut(); setUser(null); setIsGuest(false); setRolls([]); };
  const handleSaveDeviceName = (name) => { localStorage.setItem('ksf_device_name', name); setDeviceName(name); };
  const handleSaveRoll = async (e) => { e.preventDefault(); const id = `KSF-${Math.floor(Math.random() * 1000000)}`; const newRoll = { ...formData, product_id: id, status: 'in_stock' }; try { await DataService.addRoll(newRoll, deviceName); setPrintData(newRoll); fetchData(); setFormData({ customer_name: '', quality: '', gsm: '', color: '', width_inches: '', length_meters: '', net_weight: '', gross_weight: '' }); } catch (err) { alert('Error: ' + err.message); } };
  const handleDispatch = async (id) => { await DataService.updateRoll(id, { status: 'dispatched', dispatched_at: new Date() }, deviceName); fetchData(); };
  const handleDeleteRoll = async (id) => { await DataService.deleteRoll(id); fetchData(); };
  const handleEditRoll = async (updates) => { await DataService.updateRoll(updates.id, updates, deviceName); setEditRoll(null); fetchData(); };
  const handleMaterialUpdate = async (id, qty, isAdd) => { await DataService.updateRawMaterial(id, qty, isAdd, deviceName); fetchData(); };
  const handleAddMaterial = async (name) => { await DataService.addRawMaterial(name); fetchData(); };
  const handleExport = (data = rolls) => { const ws = XLSX.utils.json_to_sheet(data); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, "Sheet1"); XLSX.writeFile(wb, "KSF_Data.xlsx"); };

  if (!user && !isGuest) { return (<div className="h-[100dvh] flex items-center justify-center bg-slate-50 p-6"><div className="bg-white p-8 rounded-2xl shadow-xl max-w-sm w-full text-center border border-gray-100"><img src="/logo.png" className="h-24 w-auto mx-auto mb-8 object-contain" alt="KSF" /><h1 className="text-2xl font-bold mb-2 text-gray-900">KSF Inventory</h1><p className="text-gray-500 mb-8">Manage your factory floor efficiently.</p><button onClick={handleLogin} className="w-full bg-blue-600 text-white py-3.5 rounded-xl font-bold mb-3 hover:bg-blue-700 active:scale-95 transition-all shadow-lg shadow-blue-200">Login with Google</button><button onClick={handleGuestEntry} className="w-full bg-white text-gray-700 py-3.5 rounded-xl font-bold hover:bg-gray-50 transition border border-gray-200 flex items-center justify-center gap-2"><Eye size={20}/> Monitor Only (Guest)</button></div></div>); }
  if (user && !deviceName && !isGuest) { return <DeviceNameModal onSave={handleSaveDeviceName} />; }

  return (
    <div className="min-h-[100dvh] bg-slate-50 font-sans pb-10">
      <Header user={user} isGuest={isGuest} deviceName={deviceName} onLogout={handleLogout} setTab={setActiveTab} activeTab={activeTab} />
      <main className="max-w-7xl mx-auto p-4 md:p-6 animate-in fade-in duration-500">
        {loading ? ( <div className="flex justify-center p-12"><div className="animate-spin rounded-full h-10 w-10 border-b-2 border-blue-600"></div></div> ) : (
            <>
                {activeTab === 'dashboard' && <Dashboard rolls={rolls} materials={materials} />}
                {activeTab === 'entry' && <NewProductView formData={formData} setFormData={setFormData} onSubmit={handleSaveRoll} />}
                {activeTab === 'stock' && <StockView rolls={rolls} onPrint={setPrintData} onExport={() => handleExport(rolls)} onSelectRoll={setEditRoll} />}
                {activeTab === 'dispatch' && <DispatchView rolls={rolls} isGuest={isGuest} deviceName={deviceName} onDispatch={handleDispatch} />}
                {activeTab === 'history' && <HistoryView rolls={rolls} onSelectRoll={setEditRoll} onExport={handleExport} />}
                {activeTab === 'materials' && <MaterialsView materials={materials} isGuest={isGuest} onUpdate={handleMaterialUpdate} onAdd={handleAddMaterial} />}
            </>
        )}
      </main>
      {printData && <LabelPrint data={printData} onClose={() => setPrintData(null)} />}
      {editRoll && <EditModal roll={editRoll} isGuest={isGuest} onClose={() => setEditRoll(null)} onSave={handleEditRoll} onDelete={handleDeleteRoll} />}
    </div>
  );
}